# @package _global_
defaults:
  - benchmark: simple_lean_test
  - eval_settings: codet5_beam_16
  - env_settings: bm25_retrieval
  - override hydra/job_logging: 'disabled'

log_dir: .log/proofs_logs/debug_prop_lean4_smoke_2

eval_settings:
  proof_dump_dir: .log/proofs_dumps/debug_prop_lean4_smoke_2
  model_name: <override-with-trained-model-path>
  checkpoint_dir: .log/checkpoints/debug_prop_lean4_smoke_2
  should_checkpoint: True
  proof_retries: 1
  timeout_in_secs: 60
  max_proof_depth: 20
  width: 16
  model_parallelism: 1
  temperature: 0.75
  do_sample: True
  search_params:
    beam_width: 16

benchmark:
  name: debug_prop_lean4_smoke_2
  timeout_per_theorem_in_secs: 180
  datasets:
  - project: src/proof_wala/data/proofs/lean/lean4_proj
    files:
    - path: Lean4Proj/DebugSmoke.lean
      theorems:
      - prop_id
      - prop_and_intro
